name: Validate - Main

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    uses: ./.github/workflows/_build-and-test.yml
    with:
      solution_file: Maliev.SupplierService.slnx
      extra_args: -p:SharedLibraryVersion=1.0.*
    secrets:
      gitops_pat: ${{ secrets.GITOPS_PAT }}
